modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
issueTrackerURL="https://github.com/JustRed23/Paint-mod/issues"

[[mods]]
modId="paint"
version="${file.jarVersion}"
displayName="Paint"
logoFile="paint.png"
credits=""
authors="JustRed23 and friends"

description='''
Ever felt like there is a need for more colors? Well, this mod adds ALL the colors to Minecraft!
'''

[[dependencies.paint]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.paint]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
